# Generated by Django 3.0.4 on 2020-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productimage',
            name='isa',
            field=models.BooleanField(default=True),
        ),
    ]
