# Generated by Django 3.0.4 on 2020-03-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200330_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='isa',
        ),
    ]
